#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2022 TeamUltroid
#
# This file is a part of < https://github.com/TeamUltroid/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.


echo "

 _   _ _    ___________ _____ _____ _   _ _____ _____ 
| | | | |  |_   _| ___ \  _  /  ___| | | |_   _|_   _|
| | | | |    | | | |_/ / | | \ `--.| |_| | | |   | |  
| | | | |    | | |    /| | | |`--. \  _  | | |   | |  
| |_| | |____| | | |\ \\ \_/ /\__/ / | | |_| |_  | |  
 \___/\_____/\_/ \_| \_|\___/\____/\_| |_/\___/  \_/  
                                                      
                                            
JustRex.t.me

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py && python3 main.py ; else python3 -m pyUltroid ; fi
